### DISCUSSION TITLE
Use rocklets in DESCRIPTION and update GHA workflow accordingly

### DISCUSSION THREAD

**Discussion by GegznaV** [r-hyperspec/hyperSpec#37] [Ideas]
if you use devtools::document() without specifying roclets, it will use the roclets specified in the DESCRIPTION
  So should we update all out DESCRIPTION files to include rocklets and then update GHA workflow to use
  ```yaml
      - name: Roxygenize
        run: |
          devtools::document()
        shell: Rscript {0}
```
instead of
```yaml
      - name: Roxygenize
        run: |
          devtools::document(roclets = c('rd', 'collate', 'namespace'))
          devtools::document(roclets = c('vignette'))
        shell: Rscript {0}
```
?

Bryan Hanson 
I like this approach as among other things it makes the workflows simpler.

Vilmantas Gegzna  
We have to test it with `hyperSpec` as here are 2 rows for rocklets. There was some kind of issues that led to having  devtools::document() used 2 times.

Claudia Beleites 
> I was about to try it with `hySpc.read.spe` on your feature branch

Claudia Beleites  
(then some phone calls came in...)

Vilmantas Gegzna 
Is it possible to get the rocklets programmatically?
As in some workflows, we shouldn't build vignettes as this is an unnecessary step.
